### ISSUE TITLE
Creating a ratatosk mail/domain

### ISSUE THREAD

**Issue by EliasSchaut** [TrueDoctor/ratatosk#12]
For example Pinterest and a maximum coolnessfactor

**Comment by Ma27** [comment]
Have we reached consensus on which domain to buy?

**Comment by TrueDoctor** [comment]
We have already collected some ideas, like i.e. rask.world but have not reached a conclusion yet. I suggest a price range of up to 20€ (could be more) which I would cover.

**Comment by Ma27** [comment]
As I somehow get regular paychecks, I'd also contribute a bit of money, so we can enhance the monthly budget for that :D
